### ISSUE TITLE
Generating Gray Scale Images and Normal Maps

### ISSUE THREAD

**Issue by brassel** [jspenmar/slowtv_monodepth#3]
I am not an expert of depth estimation, but I would really like to try your code with the many applications in the 3D area.
But these applications use depth estimation in a grayscale format.
I have found this comment in the code for the [MiDaS depth estimation](https://github.com/isl-org/MiDaS/blob/bdc4ed64c095e026dc0a2f17cabb14d58263decb/run.py#L257C2-L257C2)

```
    parser.add_argument('--grayscale',
                        action='store_true',
                        help='Use a grayscale colormap instead of the inferno one. Although the inferno colormap, '
                             'which is used by default, is better for visibility, it does not allow storing 16-bit '
                             'depth values in PNGs but only 8-bit ones due to the precision limitation of this '
                             'colormap.'
                        )
```

I guess that your code also generates an "inferno color map", does it not?
Could it also feature such a parameter and generate the result in the grayscale format?
And also would it be possible to create a normal map from your result?
Would you consider adding these options?

**Comment by jspenmar** [comment]
Hi,

The current `quickstart` code can either save the disparity maps as an `png` (based on the `turbo` colormap)  or as an `npz` file with the raw disparity values. Is this not equivalent to what MiDaS is doing (albeit as an `npz` instead of a 16-bit `png`)?

https://github.com/jspenmar/slowtv_monodepth/blob/70fb69dfeaed1d9d3c346abd8a76e9fb9030cd55/api/quickstart/run.py#L75-L85

The following snippet instead saves the depth maps in the MapFreeReloc format (i.e. a `png` in millimetres).

https://github.com/jspenmar/slowtv_monodepth/blob/70fb69dfeaed1d9d3c346abd8a76e9fb9030cd55/api/mapfree/generate_preds.py#L102-L105

Regarding the surface normals, https://stackoverflow.com/a/75274993 seems like a good starting point. I've recently started a new job, so I don't have as much free time to test and add this at the moment. 

Kind regards,
Jaime
