### ISSUE TITLE
Export  estimate Colmap intrinsics failed

### ISSUE THREAD

**Issue by z-x-j** [jspenmar/slowtv_monodepth#4]
When I use python api/data/preprocess/export_slow_tv.py --n-proc 16  to export the Colmap intrinsics, I encounter an error.
RuntimeError: -> Tried [42, 195, 335, 558, 724] and they all failed!!How should I resolve this?

**Comment by z-x-j** [comment]
"I found during debugging that on line 209 of devkits/slow_tv.py, subprocess.run cannot run."
code:      
  subprocess.run([
            'colmap', 'feature_extractor', '--ImageReader.single_camera', '1',  # Same cam for whole sequence.
            '--database_path', db_path, '--image_path', img_dir,
        ])

**Comment by jspenmar** [comment]
Hi!

Sometimes this can simply be due to the feature matching failing. You can try changing the random seeds used to select the sub-sequence processed by Colmap. Does it fail on all sequences, or just on some?

The other thing I would recommend is running the commands yourself in the command line to check the output in the terminal. 

Kind regards,
Jaime

**Comment by z-x-j** [comment]
I tried random seeds within the range of 1 to 1000 with intervals of 10, but it failed. Is it because I haven't installed COLMAP?  I'm looking forward to your response.

**Comment by jspenmar** [comment]
In order to run the Colmap you have to have installed it first. You can find the instructions [here](https://colmap.github.io/install.html)

**Comment by z-x-j** [comment]
"Thank you for your guidance; I solved the issue using the 'sudo apt install colmap' command. Thank you."
